### ISSUE TITLE
ImportError: undefined symbol: ffi_closure_alloc, version LIBFFI_CLOSURE_7.0

### ISSUE THREAD

**Issue by pandadom** [felixdittrich92/OnnxTR#23]
### Bug description

I am encountering an ImportError related to ffi_closure_alloc while trying to run my script using a virtual environment. This issue seems to be linked to the libffi library. Despite several attempts to reinstall OnnxTR and the Python venv, the problem persists.

### Code snippet to reproduce the bug

```
from onnxtr.io import DocumentFile
# PDF
pdf_doc = DocumentFile.from_pdf("input.pdf")
```

### Error traceback

```
Traceback (most recent call last):
  File "/mnt/nvme01/home/workspace/documentPreprocessing/dotr/doctrOnnxtr.py", line 4, in <module>
    from onnxtr.io import DocumentFile
  File "/mnt/nvme01/home/workspace/documentPreprocessing/dotr/venvCPU3.9/lib/python3.9/site-packages/onnxtr/__init__.py", line 1, in <module>
    from . import io, models, contrib, transforms, utils
  File "/mnt/nvme01/home/workspace/documentPreprocessing/dotr/venvCPU3.9/lib/python3.9/site-packages/onnxtr/io/__init__.py", line 4, in <module>
    from .pdf import *
  File "/mnt/nvme01/home/workspace/documentPreprocessing/dotr/venvCPU3.9/lib/python3.9/site-packages/onnxtr/io/pdf.py", line 9, in <module>
    import pypdfium2 as pdfium
  File "/mnt/nvme01/home/workspace/documentPreprocessing/dotr/venvCPU3.9/lib/python3.9/site-packages/pypdfium2/__init__.py", line 4, in <module>
    import pypdfium2._library_scope
  File "/mnt/nvme01/home/workspace/documentPreprocessing/dotr/venvCPU3.9/lib/python3.9/site-packages/pypdfium2/_library_scope.py", line 6, in <module>
    import pypdfium2.raw as pdfium_c
  File "/mnt/nvme01/home/workspace/documentPreprocessing/dotr/venvCPU3.9/lib/python3.9/site-packages/pypdfium2/raw.py", line 5, in <module>
    from pypdfium2_raw.bindings import *
  File "/mnt/nvme01/home/workspace/documentPreprocessing/dotr/venvCPU3.9/lib/python3.9/site-packages/pypdfium2_raw/__init__.py", line 5, in <module>
    from pypdfium2_raw.bindings import *
  File "/mnt/nvme01/home/workspace/documentPreprocessing/dotr/venvCPU3.9/lib/python3.9/site-packages/pypdfium2_raw/bindings.py", line 6, in <module>
    import ctypes
  File "/usr/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: /usr/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so: undefined symbol: ffi_closure_alloc, version LIBFFI_CLOSURE_7.0
```

### Environment

OS: Ubuntu
python version 3.9 and 3.10 (same error in both)
LibVersion (OnnxTR): 0.3.2
Onnxruntime version: 1.18.1

**Comment by felixdittrich92** [comment]
Hi @pandadom :wave:;

Thanks for reporting :+1: 

@mara004 Have you seen this error any time before ? :sweat_smile: 

@pandadom Would it be possible to set up a anaconda environment instead of a python venv and check if the issue persists ?

**Comment by felixT2K** [comment]
Hi @pandadom  nice that it solved your issue :) 👍🏼 
So i think anything with your venv's was broken in general 😅

**Comment by felixdittrich92** [comment]
btw always happy about support with a star :star: if you like the repo :D

**Comment by mara004** [comment]
> @mara004 Have you seen this error any time before ? 😅

> So i think anything with your venv's was broken in general 😅

No, but we can see from the traceback that ctypes failed to import, and that's an integral part of python's stdlib, so yes, something must have been wrong on the caller side.

Anyway, glad you've found an approach that works.

**Comment by mara004** [comment]
FWIW, here's a SO question with the same error, but unfortunately none of the answers seem right: https://stackoverflow.com/questions/75537409/importerror-with-ffi-closure-alloc-and-libffi-closure-7-0

From the sound of the error message, python tries to load an incompatible libffi library, so maybe misconfigured `LD_LIBRARY_PATH` or something.

**Comment by felixT2K** [comment]
> FWIW, here's a SO question with the same error, but unfortunately none of the answers seem right: https://stackoverflow.com/questions/75537409/importerror-with-ffi-closure-alloc-and-libffi-closure-7-0
> 
> From the sound of the error message, python tries to load an incompatible libffi library, so maybe misconfigured `LD_LIBRARY_PATH` or something.

Yeah i have read this also but this is a known problem with TensorFlow and with OnnxTR no TF or PyTorch is required so this was not a possible reason.

**Comment by mara004** [comment]
> Yeah i have read this also but this is a known problem with TensorFlow and with OnnxTR no TF or PyTorch is required so this was not a possible reason.

I don't think this is specific to TF. It's about ctypes, which TF happens to import also.
If python tries to load an incompatible libffi, ctypes fails to import.

> I think anything in the venv's was simple broken because otherwise it should also not work with a conda env :D

Yes, yet it would be interesting to find out how/why it was broken. In the SO thread, for instance, it looks shady to me how the reporter alters `LD_LIBRARY_PATH`.
